Repository AudiusProject/audius-docker-compose, pull requests merged in 2022-08, with the labels that each got.

#46 Bump to release v0.3.63
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#47 release-v0.3.63 with sql trigger fix
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#48 Revert "release-v0.3.63 with sql trigger fix"
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#49 release-v0.3.63 with sql trigger fix
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#50 Make audius_discprov_url required and add blurb about logging
  README.md
  common-services.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/S

#51 Revert "Make audius_discprov_url required and add blurb about logging"
  README.md
  common-services.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/S

#53 Re-enable "Make audius_discprov_url required and add blurb about logging"
  README.md
  common-services.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/S

#54 Bump to release v0.3.64
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#57 Reduce maxNumberSecondsPrimaryRemainsUnhealthy value for staging from 24hr to 2hr
  creator-node/stage.env
Labels: size/XS

#58 Add entity manager address for prod/stage DP
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS

#59 [INF-225][INF-232] Log settings
  audius-cli
Labels: size/M

#60 Bump to version 0.3.65
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#61 Enable orphaned data recovery jobs on staging
  creator-node/stage.env
Labels: size/XS
