Repository AudiusProject/audius-docker-compose, pull requests merged in 2022-07, with the labels that each got.

#33 Updated health checks for content node to consume async status polling
  sp-utilities/creator-node/README.md
  sp-utilities/creator-node/apiSigning.js
  sp-utilities/creator-node/healthChecks.js
Labels: size/L

#35 Add git log
  audius-cli
Labels: size/S

#37 Add a pull to speed up deploy
  audius-cli
Labels: size/S

#36 Explicitly specify postgres user and password in compose config
  common-services.yml
Labels: size/XS

#38 [PLAT-223] Add chain to discovery docker compose
  audius-cli
  discovery-provider/chain/spec.json
  discovery-provider/docker-compose.yml
Labels: size/XL

#41 Default write quorum to staging=true, prod=false
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS

#42 Lock postgres port down only to host
  common-services.yml
Labels: size/XS

#43 Bump to version 0.3.62
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#44 Update discovery node SHA with hotfix
  discovery-provider/docker-compose.yml
Labels: size/XS

#45 Lower state monitoring job frequency
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS
