Repository AudiusProject/audius-docker-compose, pull requests merged in 2022-10, with the labels that each got.

#103 Disable premium content on stage
  creator-node/stage.env
Labels: size/XS

#104 add PR template
  .github/pull_request_template.md
Labels: size/XS

#107 Bump staging ODR and prod syncs + make others consistent
  creator-node/prod.env
  creator-node/stage.env
Labels: size/S

#108 update stage nethermind key config
  discovery-provider/stage.env
Labels: size/XS

#109 Update pull_request_template.md
  .github/pull_request_template.md
Labels: size/XS

#110 Add user verifier addr to discovery
  discovery-provider/prod.env
Labels: size/XS

#111 Add stage dn verified addr
  discovery-provider/stage.env
Labels: size/XS

#112 Set gas price to 0 for free txs
  discovery-provider/chain/config.cfg
Labels: size/XS

#69 Split out discovery provider into two containers
  audius-cli
  discovery-provider/docker-compose.yml
Labels: size/M

#113 Hotfix for commit hash
  discovery-provider/docker-compose.yml
Labels: size/XS

#114 lower staging CN statemachine queue concurrency
  creator-node/stage.env
Labels: size/XS

#115 CN track upload hotfix
  creator-node/docker-compose.yml
Labels: size/XS

#116 Unlisted track upload hotfix
  discovery-provider/docker-compose.yml
Labels: size/XS

#117 Enable prod CN content cache
  creator-node/prod.env
Labels: size/XS

#118 Disable ODR + forceWipe on stage CN
  creator-node/stage.env
Labels: size/XS

#119 Disable orphaned data recovery prod
  creator-node/prod.env
Labels: size/XS

#121 v0.3.68 Content node updates 2
  creator-node/docker-compose.yml
Labels: size/XS

#122 v0.3.68 Hotfix - Discovery Node Migration fix
  discovery-provider/docker-compose.yml
Labels: size/XS

#123 CN Prod - change CN tag & set maxUpdateReplicaSetJobConcurrency = 0
  creator-node/docker-compose.yml
  creator-node/prod.env
Labels: size/XS

#100 INF-266 Add Postgres and ES Prometheus exporters
  common-services.yml
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/L

#125 Disable reconfigModePrimaryOnly for staging CN
  creator-node/stage.env
Labels: size/XS

#124 Update CN tag, Unset maxUpdateReplicaSetJobConcurrency, set reconfigModePrimaryOnly=true, lower maxRecurringRequestSyncJobConcurrency
  creator-node/docker-compose.yml
  creator-node/prod.env
Labels: size/XS

#126 Disable prod reconfig
  creator-node/prod.env
Labels: size/XS

#127 Enable disk prune for stage
  creator-node/stage.env
Labels: size/XS

#128 CN Disk envvar cleanup STAGE
  creator-node/stage.env
Labels: size/XS

#129 Update prod CN envvars
  creator-node/docker-compose.yml
  creator-node/prod.env
Labels: size/XS

#130 Default mergePrimaryAndSecondaryEnabled to true
  creator-node/prod.env
Labels: size/XS

#131 Add entity manager address to stage identity
  identity-service/stage.env
Labels: size/XS

#132 Update entity manager address for stage
  discovery-provider/stage.env
Labels: size/XS

#133 v0.3.68 hotfix update 10/28/22
  creator-node/docker-compose.yml
  creator-node/prod.env
Labels: size/XS

#135 CN: (stage) recoverOrphanedDataQueueRateLimitJobsPerInterval from 0 to 1; (prod) maxRecurringRequestSyncJobConcurrency from 15 to 16
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS
