Repository AudiusProject/audius-docker-compose, pull requests merged in 2022-11, with the labels that each got.

#137 [INF-307] Enable openresty by default on stage
  discovery-provider/stage.env
Labels: size/XS

#134 Change to always restart
  common-services.yml
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#139 Revert SHA back to v0.3.69 release
  creator-node/docker-compose.yml
Labels: size/XS

#140 Cleanup CN configs
  creator-node/prod.env
  creator-node/stage.env
Labels: size/L

#138 Swap extra hosts from indexer to server
  discovery-provider/docker-compose.yml
Labels: size/XS

#141 update cn tag to release-v0.3.69-cn-patch
  creator-node/docker-compose.yml
Labels: size/XS

#142 Turn off the background disk delete
  creator-node/prod.env
Labels: size/XS

#145 Some minor cleanup for auto upgrade exposing
  audius-cli
Labels: size/M

#146 Disable opentelemetry on prod CN
  creator-node/prod.env
Labels: size/XS

#148 Update pull_request_template.md
  .github/pull_request_template.md
Labels: size/XS

#147 Hotfix db leak in backfill indexers
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#149 hotfix discovery for es raise_if_stale
  discovery-provider/docker-compose.yml
Labels: size/XS
