Repository AudiusProject/audius-docker-compose, pull requests merged in 2022-12, with the labels that each got.

#143 Enable entity manager reads on CNs
  creator-node/prod.env
  creator-node/stage.env
  identity-service/stage.env
Labels: size/XS

#152 Update dump/restore owner and privileges
  discovery-provider/seed.sh
Labels: size/XS

#153 Add parallel restore
  discovery-provider/seed.sh
Labels: size/XS

#157 Ship dummy counter env to trigger restart
  discovery-provider/prod.env
Labels: size/XS

#161 Update sp utils README
  .gitignore
  sp-utilities/creator-node/README.md
Labels: size/XS

#163 Update backfill migration in 0.3.72
  discovery-provider/docker-compose.yml
Labels: size/XS

#154 Add commit as env var
  audius-cli
Labels: size/M

#160 Change how gas is estimated
  sp-utilities/claim/claim.js
Labels: size/S

#156 Content node config changes for v0.3.72
  creator-node/prod.env
Labels: size/XS

#165 Enable stage CN backgroundDiskCleanupDeleteEnabled
  creator-node/stage.env
Labels: size/XS

#167 Update general admission env vars
  identity-service/prod.env
  identity-service/stage.env
Labels: size/XS

#168 CN release-v0.3.73-patch-v0.3.72
  creator-node/docker-compose.yml
  creator-node/stage.env
Labels: size/XS

#166 Hotfix remove caching for unclaimed ID
  discovery-provider/docker-compose.yml
Labels: size/XS

#169 hotfix handle lowercase
  discovery-provider/docker-compose.yml
Labels: size/XS

#171 Turn off CN state machines
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS

#172 Re-enable CN state machine (monitor-state job)
  creator-node/prod.env
Labels: size/XS

#173 Update discovery for skip missing users fix
  discovery-provider/docker-compose.yml
Labels: size/XS
