Repository AudiusProject/audius-docker-compose, pull requests merged in 2022-05, with the labels that each got.

#1 Add elasticsearch container
  discovery-provider/docker-compose.yml
  discovery-provider/env
Labels: size/M

#2 Revert "Add elasticsearch container"
  discovery-provider/docker-compose.yml
  discovery-provider/env
Labels: size/M

#4 Revert "Revert "Add elasticsearch container""
  discovery-provider/docker-compose.yml
  discovery-provider/env
Labels: size/M

#6 Rename ENV to NETWORK and use env file over args
  README.md
  audius-cli
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  discovery-provider/seed.sh
Labels: size/M

#5 [INF-77] Support stage env
  .gitignore
  README.md
  audius-cli
  creator-node/docker-compose.yml
  creator-node/prod.env
  creator-node/stage.env
  discovery-provider/docker-compose.yml
  discovery-provider/prod.env
  discovery-provider/seed.sh
  discovery-provider/stage.env
Labels: size/L

#7 Add autoheal to DP
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#8 Add seed job prompt
  setup.sh
Labels: size/S

#12 Fix default db url
  creator-node/docker-compose.yml
  creator-node/prod.env
  creator-node/stage.env
  discovery-provider/docker-compose.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/S

#13 Final audius-cli fixes and setup prompt tweaks
  audius-cli
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  setup.sh
Labels: size/L

#16 Expose postgres port to host
  common-services.yml
Labels: size/XS

#14 Use Logspout to forward logs to Loggly
  common-services.yml
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#18 README updates + small tweaks
  ADVANCED_SETUP.md
  README.md
  creator-node/prod.env
  creator-node/stage.env
Labels: size/M
