Repository AudiusProject/audius-docker-compose, pull requests merged in 2022-06, with the labels that each got.

#17 [INF-93] disable rsyslog in favor of logspout
  creator-node/prod.env
  creator-node/stage.env
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS

#20 Bump to v0.3.59
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#21 CON-200 Add snapbackMaxLastSuccessfulRunDelayMs
  creator-node/stage.env
Labels: size/XS

#24 Bump to version 0.3.60
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#23 default elasticsearch enabled. make ES ram limit configurable
  discovery-provider/docker-compose.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/S

#22 [INF-132] Add support for identity service
  audius-cli
  identity-service/docker-compose.yml
  identity-service/prod.env
  identity-service/stage.env
Labels: size/L

#26 Add SP Utilities folder to compose + add section in README
  README.md
  sp-utilities/README.md
  sp-utilities/claim/README.md
  sp-utilities/claim/claim.js
  sp-utilities/creator-node/README.md
  sp-utilities/creator-node/apiSigning.js
  sp-utilities/creator-node/delistContent.js
  sp-utilities/creator-node/healthChecks.js
  sp-utilities/discovery-provider/README.md
  sp-utilities/discovery-provider/healthChecks.js
  sp-utilities/package-lock.json
  sp-utilities/package.json
Labels: size/XXL

#27 Disable snapback, enable refactored state machine
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS

#29 Fix typo
  audius-cli
Labels: size/XS

#28 Add checks for Ubuntu OS and kernel versions
  setup.sh
Labels: size/S

#25 Add contentCacheLayerEnabled=true
  creator-node/stage.env
Labels: size/XS

#31 Increase identity AUTOHEAL_INTERVAL
  identity-service/docker-compose.yml
Labels: size/XS
