Repository AudiusProject/audius-docker-compose, pull requests merged in 2022-09, with the labels that each got.

#64 CN - Increase reconfig and recurring sync concurrency for staging
  creator-node/stage.env
Labels: size/XS

#65 Increase reconfig and sync concurrency to 25 & 50
  creator-node/stage.env
Labels: size/XS

#66 Update discovery node to c54dc4
  discovery-provider/docker-compose.yml
Labels: size/XS

#70 Remove stage CN snapbackHighestReconfigMode envvar
  creator-node/stage.env
Labels: size/XS

#71 Increase stage CN snapbackUsersPerJob from 1k to 2k
  creator-node/stage.env
Labels: size/XS

#72 Add OpenTelemetry Env Vars
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS

#75 Bump to release v0.3.66
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#74 Unset snapbackHighestReconfigMode for prod CN
  creator-node/prod.env
Labels: size/XS

#77 Reduce prod sync/reconfig concurrency + enable mergePrimary on prod & stage
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS

#78 Enable prod primary reconfig + 2s snapbackUsersPerJob
  creator-node/prod.env
Labels: size/XS

#79 Reduce prod SP state machine throughput
  creator-node/prod.env
Labels: size/XS

#80 Disable mergePrimaryAndSecondaryEnabled prod
  creator-node/prod.env
Labels: size/XS

#81 Bump SP snapbackUsersPerJob
  creator-node/prod.env
Labels: size/XS

#82 Up statemachine throughput a littttle bit (at most 25%)
  creator-node/prod.env
Labels: size/XS

#83 Enable mergePrimaryAndSecondaryEnabled on all SPs
  creator-node/prod.env
Labels: size/XS

#84 Increase SP reconfig/sync queue concurrency from 5/10 to 7/14 and increase snapbackUsersPerJob from 2k to 3k
  creator-node/prod.env
Labels: size/XS

#85 Increase SP snapbackUsersPerJob from 3k to 4k
  creator-node/prod.env
Labels: size/XS

#86 Set reconfig blacklist to cn7 for stage
  creator-node/stage.env
Labels: size/XS

#88 Lower staging export clockvalue range for better testing
  creator-node/stage.env
Labels: size/XS

#89 [PLAT-242] Prepare nethermind for stage
  .gitignore
  audius-cli
  discovery-provider/chain/config.cfg
  discovery-provider/chain/spec_template.json
  discovery-provider/docker-compose.yml
  discovery-provider/stage.env
Labels: size/L

#91 Run nethermind chain with DN by default
  audius-cli
Labels: size/XS

#92 Remove annoying logs
  audius-cli
Labels: size/XS

#90 Update staging to use goerli addresses
  creator-node/stage.env
  discovery-provider/stage.env
  identity-service/stage.env
Labels: size/S

#93 Update stage network id
  creator-node/stage.env
  identity-service/stage.env
Labels: size/XS

#94 Bump to version 0.3.67
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/XS

#96 Remove early return in the case chain is run
  audius-cli
Labels: size/XS

#95 Add cn entity manager env vars
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS

#97 Disable entity manager replica set on stage
  creator-node/stage.env
Labels: size/XS

#87 CON-428 INF try to workaround disk contention for content node
  common-services.yml
  creator-node/docker-compose.yml
Labels: size/M

#99 INF-251 report as unhealthy for errors seen on Staging
  audius-cli
Labels: size/XS

#101 Enable premium content on stage
  creator-node/stage.env
Labels: size/XS

#102 Change CN tag only to protocol v0.3.67-patch-cn
  creator-node/docker-compose.yml
Labels: size/XS

#98 configurable mem_limit for server container
  discovery-provider/docker-compose.yml
Labels: size/XS
