Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-06, with the labels that each got.

#294 Add chain auto restart and remove block production from health
  audius-cli
  discovery-provider/chain/config.cfg
  discovery-provider/docker-compose.yml
Labels: size/S

#296 Make mediorum first by default
  creator-node/docker-compose.yml
Labels: size/XS

#295 [PLAT-917] Add docker exporter
  common-services.yml
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/M

#299 Upgrade nethermind to 1.17.4
  discovery-provider/docker-compose.yml
Labels: size/XS

#300 Enable autoheal chain
  audius-cli
  discovery-provider/docker-compose.yml
Labels: size/M

#301 Add chain ID to identity env
  identity-service/prod.env
  identity-service/stage.env
Labels: size/XS

#303 Revert version for clique_propose
  discovery-provider/docker-compose.yml
Labels: size/XS

#302 [CON-770] Turn off state machine
  creator-node/prod.env
  creator-node/stage.env
Labels: size/S
