Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-05, with the labels that each got.

#285 Move ES indexer to indexer only
  discovery-provider/docker-compose.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS

#288 PLAT-970: use latest audius nm version
  discovery-provider/docker-compose.yml
Labels: size/XS

#290 revert version
  discovery-provider/docker-compose.yml
Labels: size/XS

#291 Make CN check 500 users per 90s instead of 2000 users per minute
  creator-node/prod.env
Labels: size/XS

#287 Disable JSON RPC logs
  discovery-provider/chain/NLog.config
  discovery-provider/chain/config.cfg
  discovery-provider/docker-compose.yml
Labels: size/L

#292 Update mediorum tag to c48a2e1c48f1cf28c329cbde3cb6d9eaa4a7c541
  creator-node/docker-compose.yml
Labels: size/XS

#293 Improve SP utilities, add acdc peer check
  utilities/README.md
  utilities/creator-node/README.md
  utilities/creator-node/delistContent.js
  utilities/creator-node/delistContent/commanderHelper.js
  utilities/creator-node/delistContent/hashIds.js
  utilities/creator-node/delistContent/index.js
  utilities/discovery-provider/README.md
  utilities/discovery-provider/healthChecks.js
  utilities/package.json
Labels: size/XXL
