Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-08, with the labels that each got.

#319 Fix getGasPrice call
  utilities/claim/README.md
  utilities/claim/claim.js
Labels: size/XS

#320 [CON-802] Clean up creator-node
  audius-cli
  creator-node/docker-compose.yml
  creator-node/prod.env
  creator-node/stage.env
  utilities/creator-node/healthChecks.js
Labels: size/L

#322 Return 200 for unregistered nodes in health check
  utilities/creator-node/healthChecks.js
Labels: size/XS

#324 Run 1 iteration of Qm CID migration on prod
  creator-node/prod.env
Labels: size/XS

#325 Run unlimited Qm CID migrations
  creator-node/prod.env
Labels: size/XS

#326 Pause Qm CID migration
  creator-node/prod.env
Labels: size/XS

#327 Resume Qm CID migration
  creator-node/prod.env
Labels: size/XS

#329 PLAT-1176: cleanup relay
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/S

#331 Update common postgres shared_buffers from 512mb to 2gb
  common-services.yml
Labels: size/XS

#332 Add eth token to discovery env files
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS
