Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-07, with the labels that each got.

#305 Remove delist script
  README.md
  utilities/README.md
  utilities/creator-node/delistContent/commanderHelper.js
  utilities/creator-node/delistContent/hashIds.js
  utilities/creator-node/delistContent/index.js
  utilities/package.json
Labels: size/XL

#306 Prune according to disk space
  audius-cli
Labels: size/M

#308 Remove force recreate of chain
  audius-cli
Labels: size/XS

#310 [CON-774] Add IS_V2_ONLY flag
  audius-cli
  creator-node/docker-compose.yml
  creator-node/prod.env
  creator-node/stage.env
Labels: size/L

#312 caddy reverse proxy setup
  creator-node/Caddyfile
  creator-node/docker-compose.yml
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.yml
Labels: size/M

#311 As/plat 1136 build relay plugin
  audius-cli
  discovery-provider/docker-compose.plugins.yml
Labels: size/M

#313 [CON-789] Default content nodes to v2-only
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS

#314 Add USDC mint to config
  discovery-provider/prod.env
  discovery-provider/stage.env
  identity-service/prod.env
  identity-service/stage.env
Labels: size/XS

#315 Update eth rpcs
  creator-node/prod.env
  creator-node/stage.env
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS

#316 Allow mediorum to write legacy fs
  creator-node/docker-compose.yml
Labels: size/XS

#317 Run Qm CID migration on stage
  creator-node/stage.env
Labels: size/XS
