Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-02, with the labels that each got.

#195 Pass --force to system prune
  audius-cli
Labels: size/XS

#196 Update README to include upgrade instructions
  README.md
Labels: size/S

#192 Add function to set override path
  audius-cli
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/M

#197 Add instructions to set override path
  README.md
Labels: size/S

#198 1 second block time
  discovery-provider/chain/prod_spec_template.json
  discovery-provider/chain/stage_spec_template.json
  discovery-provider/prod.env
Labels: size/S

#199 update comms / nats / storage version
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#200 Prepend https:// to creatorNodeEndpoint
  creator-node/docker-compose.yml
Labels: size/XS

#201 Add override for set-tag
  audius-cli
Labels: size/M

#202 ignore nats in logspout
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#203 Add default prod.env file to comms container.
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#204 Update backend tag to include /segment_to_cid fix
  creator-node/docker-compose.yml
Labels: size/XS

#206 Cherry pick [PAY-915] to improve stream_cid performance
  discovery-provider/docker-compose.yml
Labels: size/XS

#208 Fix typo
  discovery-provider/docker-compose.yml
Labels: size/XS

#209 update comms version
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#205 Reset chain to 1056802
  discovery-provider/chain/prod_spec_template.json
Labels: size/XS

#211 Reset chain to 566b
  discovery-provider/chain/prod_spec_template.json
Labels: size/XS

#212 Add admin module
  audius-cli
  discovery-provider/chain/config.cfg
Labels: size/XS

#207 Add AUDIUS_IS_STAGING env var
  creator-node/stage.env
  discovery-provider/stage.env
Labels: size/XS

#215 Add stage and prod env files to nats and storage
  creator-node/docker-compose.yml
  creator-node/stage.env
  discovery-provider/docker-compose.yml
  discovery-provider/stage.env
Labels: size/XS

#214 Add ACDC nethermind host and address
  discovery-provider/prod.env
Labels: size/XS
