Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-12, with the labels that each got.

#406 Compose changes for dashboard entrypoint
  discovery-provider/docker-compose.yml
Labels: size/XS

#411 [PROTO-1458] Upgrade postgres on mediorum
  creator-node/docker-compose.yml
Labels: size/M

#412 Fix pg upgrade for corrupted mediorum dbs
  creator-node/docker-compose.yml
Labels: size/M

#414 Bump indexer start_period to 2 hours
  discovery-provider/docker-compose.yml
Labels: size/XS

#416 default to use AAO for relay on stage
  discovery-provider/stage.env
Labels: size/XS

#417 Fix using relative path to .env in pg upgrade
  audius-cli
  discovery-provider/docker-compose.yml
Labels: size/M

#418 Remove stale containers when pg upgrade fails
  audius-cli
Labels: size/XS

#419 Add payment router program ids
  discovery-provider/prod.env
  discovery-provider/stage.env
  identity-service/prod.env
  identity-service/stage.env
Labels: size/XS

#423 Improve node type detection and clean up DN containers
  audius-cli
  discovery-provider/docker-compose.yml
Labels: size/L

#420 Clean up blockscout
  audius-cli
  discovery-provider/docker-compose.plugins.blockscout.yml
Labels: size/L

#425 Remove chain container when running 'audius-cli down'
  audius-cli
Labels: size/S

#424 [PROTO-1481] Remove option to configure hosted postgres
  ADVANCED_SETUP.md
  README.md
  creator-node/prod.env
  creator-node/stage.env
  setup.sh
Labels: size/M

#426 Always prune on audius-cli upgrade
  audius-cli
Labels: size/L

#427 dev option
  audius-cli
  creator-node/dev.env
  discovery-provider/chain/dev_spec_template.json
  discovery-provider/dev.env
  identity-service/dev.env
Labels: size/XXL

#430 Limit mem and CPU on mediorum container
  creator-node/docker-compose.yml
Labels: size/XS

#410 Add metabase plugin
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.yml
Labels: size/S

#432 Consume protocol dashboard stage vs prod images
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#433 Revert protocol dashboard changes
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#431 Add ddex as plugin
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.yml
Labels: size/S

#434 Add back dashboard changes
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#435 Adds back tag changes which got bulldozed
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#429 Remove db upgrade containers post migration
  creator-node/docker-compose.yml
Labels: size/M
