Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-04, with the labels that each got.

#257 remove nats, update dms
  audius-cli
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/M

#258 update comms to use correct POA gateway
  discovery-provider/docker-compose.yml
Labels: size/XS

#259 Add until to prune
  audius-cli
Labels: size/XS

#260 Missing --filter before until
  audius-cli
Labels: size/XS

#262 Update install.sh script to pull main
  install.sh
Labels: size/XS

#243 [INF-353] Add vector.dev container
  audius-cli
  common-services.yml
  creator-node/docker-compose.yml
  creator-node/prod.env
  creator-node/stage.env
  discovery-provider/docker-compose.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
  identity-service/docker-compose.yml
  identity-service/prod.env
  identity-service/stage.env
Labels: size/M

#264 [INF-385] Move to 2w cleanup
  audius-cli
Labels: size/XS

#265 Switch to 2 weeks in hours
  audius-cli
Labels: size/XS

#266 Cherry pick until fix
  audius-cli
Labels: size/XS

#267 Update README
  README.md
Labels: size/XS

#269 Touch readme
  README.md
Labels: size/XS

#263 custom nethermind image and health check
  discovery-provider/docker-compose.yml
Labels: size/XS

#270 mediorum: tag image, run on subset of hosts
  creator-node/docker-compose.yml
  creator-node/prod.env
Labels: size/XS

#271 Update content node to 47ed0af
  creator-node/docker-compose.yml
Labels: size/XS

#272 Get rid of noise
  .gitignore
  discovery-provider/docker-compose.yml
Labels: size/XS

#273 [INF-386] Improve README
  .gitignore
  README.md
  utilities/README.md
  utilities/claim/README.md
  utilities/claim/claim.js
  utilities/creator-node/README.md
  utilities/creator-node/apiSigning.js
  utilities/creator-node/delistContent.js
  utilities/creator-node/healthChecks.js
  utilities/discovery-provider/README.md
  utilities/discovery-provider/healthChecks.js
  utilities/package-lock.json
  utilities/package.json
Labels: size/M

#268 PLAT-858: register plugins on auto upgrade
  audius-cli
Labels: size/M

#276 Add websocket connection test
  utilities/discovery-provider/healthChecks.js
  utilities/package-lock.json
  utilities/package.json
Labels: size/M

#277 Add proxy config to README
  README.md
Labels: size/S

#279 Add identity env
  setup.sh
Labels: size/XS

#278 Allow recreating of chain container to allow image upgrade
  audius-cli
Labels: size/XS

#282 Bump mediorum tag
  creator-node/docker-compose.yml
Labels: size/XS

#281 Mediorum port env
  creator-node/docker-compose.yml
Labels: size/XS

#283 Update stage rewards account
  discovery-provider/stage.env
Labels: size/XS

#284 Revert autoheal chain container
  discovery-provider/docker-compose.yml
Labels: size/XS
