Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-01, with the labels that each got.

#174 update nethermind port config
  discovery-provider/docker-compose.yml
Labels: size/XS

#175 Add entity manager address to prod identity
  identity-service/prod.env
Labels: size/XS

#179 Update CN entity manager address for stage ACDC
  creator-node/stage.env
Labels: size/XS

#180 [staging] Reduce CN state machine unhealthy peer grace period
  creator-node/stage.env
Labels: size/XS

#183 hotfix for subscription revert logic
  discovery-provider/docker-compose.yml
Labels: size/XS

#182 SPUtilities CN Healthchecks minor improvements
  sp-utilities/creator-node/healthChecks.js
Labels: size/S

#178 0.3.74 release changes - enable CN reconfig, reduce CN dbConnPool
  creator-node/prod.env
  creator-node/stage.env
Labels: size/XS

#176 [PLAT-538] Enable redis persistence
  audius-cli
Labels: size/XS

#185 Launch Chain + Comms. Upgrade Redis.
  audius-cli
  common-services.yml
  creator-node/docker-compose.yml
  discovery-provider/chain/config.cfg
  discovery-provider/chain/prod_spec_template.json
  discovery-provider/chain/stage_spec_template.json
  discovery-provider/docker-compose.yml
  discovery-provider/prod.env
  discovery-provider/stage.env
  identity-service/docker-compose.yml
Labels: size/XXL

#186 rename comms container
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#187 Version comms build with git sha.
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#189 Add logging limits
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/M

#191 Add newline
  sp-utilities/claim/README.md
Labels: size/XS

#188 Update cleanup to do system prune instead of image prune
  audius-cli
Labels: size/S

#193 Update dn patch of v0.3.75
  discovery-provider/docker-compose.yml
Labels: size/XS

#194 Update docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S
