Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-11, with the labels that each got.

#395 [PROTO-1388] Run protocol dashboard on prod
  creator-node/Caddyfile
  creator-node/docker-compose.plugins.yml
  creator-node/docker-compose.yml
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/docker-compose.yml
Labels: size/M

#397 Run uptime containers
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#400 Revert "Remove exporter containers (#398)"
  common-services.yml
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/L

#401 Fix exporter removal
  common-services.yml
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/L

#403 [PROTO-1418] Add env vars for /up UI
  creator-node/prod.env
  creator-node/stage.env
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/M

#402 Disable launching of CN plugins
  audius-cli
Labels: size/XS

#404 rm hosts addition in server
  discovery-provider/docker-compose.yml
Labels: size/XS

#408 PROTO-1448: add back remove orphans and refactor plugin startup
  audius-cli
  creator-node/docker-compose.plugins.yml
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/docker-compose.yml
Labels: size/L
