Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-03, with the labels that each got.

#217 Update 0.3.77 release
  discovery-provider/docker-compose.yml
Labels: size/XS

#220 PLAT-748: use latest nethermind image
  discovery-provider/docker-compose.yml
Labels: size/XS

#221 Update nats / storage / comms.
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#223 Pin nethermind to 1.17.0
  discovery-provider/docker-compose.yml
Labels: size/XS

#222 Update to version 0.3.78
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/S

#216 Remove NATS_STORE_DIR env var
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#225 Revert nethermind version back to 14.3
  discovery-provider/docker-compose.yml
  discovery-provider/stage.env
Labels: size/XS

#226 Hotfix removing prometheus
  discovery-provider/docker-compose.yml
Labels: size/XS

#228 Update comms image
  discovery-provider/docker-compose.yml
Labels: size/XS

#227 Update to latest v0.3.78 discovery
  discovery-provider/docker-compose.yml
Labels: size/XS

#229 Add mediorum container
  creator-node/docker-compose.yml
  creator-node/prod.env
  creator-node/stage.env
Labels: size/S

#190 [Trivial] Add a few msgs to the sp utilties
  sp-utilities/discovery-provider/healthChecks.js
Labels: size/XS

#234 Notifications cli
  audius-cli
  discovery-provider/docker-compose.notifications.yml
Labels: size/M

#236 ACDC migration chain reset again
  discovery-provider/chain/prod_spec_template.json
Labels: size/XS

#232 Cleanup newline
  audius-cli
Labels: size/XS

#238 Hotfix drop constraints on blocks
  discovery-provider/docker-compose.yml
Labels: size/XS

#239 Hotfix revert by number + stop POA indexing
  discovery-provider/docker-compose.yml
Labels: size/XS

#240 Hot fix es-indexer is_available
  discovery-provider/docker-compose.yml
Labels: size/XS

#241 Add final POA block to env
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS

#242 bypass notification txs
  discovery-provider/docker-compose.yml
Labels: size/XS

#246 Revert to 0.3.78 on content nodes
  creator-node/docker-compose.yml
Labels: size/XS

#244 Discovery notifs health
  audius-cli
  discovery-provider/docker-compose.notifications.yml
Labels: size/S

#248 Fix env file logic
  audius-cli
Labels: size/M

#250 Bump shm size to 2g
  common-services.yml
Labels: size/XS

#254 Update content node SHA to 0.3.80
  creator-node/docker-compose.yml
Labels: size/XS

#256 Hotfix re-enable track trigger
  discovery-provider/docker-compose.yml
Labels: size/XS
