Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-09, with the labels that each got.

#349 Fix merge conflicts
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/S

#350 fix indexer / server failure cycle
  discovery-provider/docker-compose.yml
Labels: size/XS

#323 [CON-806] Add back updated delist script
  utilities/README.md
  utilities/creator-node/apiSigning.js
  utilities/creator-node/delistContent/hashIds.js
  utilities/creator-node/delistContent/index.js
  utilities/package.json
Labels: size/L

#352 Update solana RPC for stage
  discovery-provider/stage.env
Labels: size/XS

#351 [PROTO-1232] Add radix container
  creator-node/docker-compose.yml
  creator-node/prod.env
  creator-node/stage.env
Labels: size/S

#353 Add caddy cache
  creator-node/Caddyfile
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/M

#358 Merge dev into main
  creator-node/Caddyfile
Labels: size/S

#359 Add back caddy cache with range header in key
  creator-node/Caddyfile
Labels: size/S

#357 launch plugins after prune
  audius-cli
Labels: size/XS

#330 Add SLA auditor container, clean up plugins
  audius-cli
  discovery-provider/docker-compose.notifications.yml
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/prod.env
Labels: size/L

#360 Match plugin tags to normal tags
  discovery-provider/docker-compose.plugins.yml
Labels: size/XS

#362 Update to v0.4.9 except identity
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#363 No separate notifs env
  discovery-provider/docker-compose.plugins.yml
Labels: size/XS

#364 Update to v0.4.10
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/S

#366 Push v0.4.10 to main for SPs
  audius-cli
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.notifications.yml
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/docker-compose.yml
  discovery-provider/prod.env
  identity-service/docker-compose.yml
Labels: size/L

#368 fix 0.4.10 sha
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#361 [PROTO-1189] Add healthz to common services
  common-services.yml
  creator-node/Caddyfile
  creator-node/docker-compose.yml
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.yml
Labels: size/S

#369 Update to v0.4.11
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/S

#370 Fix network name for healthz in discovery
  discovery-provider/docker-compose.yml
Labels: size/XS

#371 Pin the healthz version
  common-services.yml
Labels: size/XS

#372 Update to v0.4.11 on main
  common-services.yml
  creator-node/Caddyfile
  creator-node/docker-compose.yml
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/M

#375 rm dedupe
  audius-cli
Labels: size/XS

#377 No recreate chain container
  audius-cli
Labels: size/XS

#378 add trpc demo as plugin
  audius-cli
  discovery-provider/docker-compose.plugins.yml
Labels: size/S

#379 Fix release 4.20 foundation tag
  discovery-provider/docker-compose.yml
Labels: size/XS

#373 ACDC blockscout
  .gitignore
  audius-cli
  discovery-provider/docker-compose.plugins.blockscout.yml
  discovery-provider/docker-compose.yml
Labels: size/L
