Repository AudiusProject/audius-docker-compose, pull requests merged in 2023-10, with the labels that each got.

#381 move relay into main compose file
  audius-cli
  discovery-provider/docker-compose.plugins.yml
  discovery-provider/docker-compose.yml
Labels: size/M

#382 Make audius-cli set-tag disable auto-upgrade
  audius-cli
Labels: size/XS

#383 Add protocol dashboard as discovery plugin
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.plugins.yml
Labels: size/S

#385 Add indexer mem limit
  discovery-provider/docker-compose.yml
Labels: size/XS

#384 [PROTO-1349] Continuous deployment for healthz
  common-services.yml
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#388 Make auto-upgrade pull use a hard reset
  audius-cli
Labels: size/M

#391 CN plugins
  audius-cli
  creator-node/Caddyfile
  creator-node/docker-compose.plugins.yml
  discovery-provider/docker-compose.plugins.yml
Labels: size/M

#392 fix upgrade
  audius-cli
Labels: size/XS

#393 Recreate plugins on launch
  audius-cli
Labels: size/XS

#394 Lower disk usage threshold when pruning in audius-cli
  audius-cli
Labels: size/XS
