Repository AudiusProject/audius-docker-compose, pull requests merged in 2024-03, with the labels that each got.

#488 Revert "Allow containers via docker in docker host (#487)"
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#489 Reseed exposed postgres (discovery + content)
  audius-cli
Labels: size/M

#490 Create dn db if needed
  audius-cli
Labels: size/XS

#491 Remove db size check
  audius-cli
Labels: size/S

#492 PAY-2203: add solana-relay to discovery
  discovery-provider/docker-compose.yml
Labels: size/S

#493 right port for solana relay
  discovery-provider/docker-compose.yml
Labels: size/XS

#496 Remove postgres reseeding
  audius-cli
Labels: size/S

#494 Remove all unnecessary published ports
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#497 Reopen 5000 on openresty
  discovery-provider/docker-compose.yml
Labels: size/XS

#495 Increase healthcheck timeout on elasticsearch
  discovery-provider/docker-compose.yml
Labels: size/XS

#499 Revert "Increase healthcheck timeout on elasticsearch"
  discovery-provider/docker-compose.yml
Labels: size/XS

#501 Add healthcheck start period in a way that doesn't cause merge conflicts
  discovery-provider/docker-compose.yml
Labels: size/XS

#500 Make DDEX work with protocol changes
  ddex/dev.env
  ddex/docker-compose.yml
  ddex/prod.env
  ddex/stage.env
Labels: size/S
