Repository AudiusProject/audius-docker-compose, pull requests merged in 2024-04, with the labels that each got.

#502 Pass network instead of node_env to ddex
  ddex/docker-compose.yml
Labels: size/XS

#503 Keep tag when auto-upgrading
  audius-cli
Labels: size/S

#504 Add auto-seed flag to audius-cli
  audius-cli
  discovery-provider/seed.sh
Labels: size/M

#505 Scale back number of discovery node eventlet gunicorn workers
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS
