Repository AudiusProject/audius-docker-compose, pull requests merged in 2024-05, with the labels that each got.

#506 Remove empty chain spec directories
  audius-cli
Labels: size/S

#507 Add crm tool
  discovery-provider/docker-compose.yml
Labels: size/S

#508 Fix health check
  utilities/discovery-provider/healthChecks.js
Labels: size/XS

#509 add uploads and rewards
  discovery-provider/docker-compose.yml
Labels: size/M

#510 add mri
  discovery-provider/docker-compose.yml
Labels: size/S

#511 ddex: processor
  .gitignore
  ddex/Caddyfile
  ddex/data/sources.example.json
  ddex/docker-compose.yml
Labels: size/L

#512 turn on stage discovery listens
  creator-node/stage.env
Labels: size/XS
