Repository AudiusProject/audius-docker-compose, pull requests merged in 2024-01, with the labels that each got.

#438 Update docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#439 [PROTO-1557] Make /ddex use container instead of pre-compiled dist
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.yml
Labels: size/XS

#440 Add conditional matchers for discovery Caddy directives
  discovery-provider/Caddyfile
Labels: size/S

#441 DDEX env
  discovery-provider/docker-compose.yml
Labels: size/XS

#444 Update DN to latest
  discovery-provider/docker-compose.yml
Labels: size/S

#445 Extend devnet hostnames to allow proper wildcard CN
  creator-node/dev.env
  creator-node/docker-compose.yml
  discovery-provider/dev.env
  discovery-provider/docker-compose.yml
  identity-service/dev.env
  identity-service/docker-compose.yml
Labels: size/M

#446 Mount auto upgrade logs to vector container
  audius-cli
  discovery-provider/docker-compose.yml
Labels: size/XS

#449 Test internet access from server and chain
  audius-cli
Labels: size/S

#450 DDEX web on standalone node
  discovery-provider/Caddyfile
  discovery-provider/docker-compose.yml
Labels: size/S

#452 Recreate chain if unable to access internet
  audius-cli
Labels: size/M

#443 Standalone openresty container
  discovery-provider/docker-compose.yml
Labels: size/S

#453 [PROTO-1606] Rollout pg upgrade to ~1/6th of DNs
  audius-cli
Labels: size/S

#454 Recreate other containers w change
  audius-cli
Labels: size/S

#455 DDEX mongo container
  discovery-provider/docker-compose.yml
Labels: size/M

#456 Fix race conditions in upgrade for SPs
  audius-cli
Labels: size/M

#457 [PROTO-1606] Continue postgres rollout to ~half of DNs
  audius-cli
Labels: size/XS

#459 [PROTO-1606] Finish postgres upgrade rollout
  audius-cli
Labels: size/XS

#460 Update ddex web image
  discovery-provider/docker-compose.yml
Labels: size/XS

#458 Add DDEX services to docker compose
  .gitignore
  discovery-provider/docker-compose.yml
Labels: size/M

#462 Increase chain max peers
  discovery-provider/chain/config.cfg
Labels: size/XS

#463 [PROTO-1606] Remove postgres upgrade code
  audius-cli
  discovery-provider/docker-compose.yml
Labels: size/L
