Repository AudiusProject/audius-docker-compose, pull requests merged in 2024-02, with the labels that each got.

#464 Add bootnodes for peer discovery
  audius-cli
  discovery-provider/docker-compose.yml
Labels: size/XS

#461 Add DDEX publisher service
  discovery-provider/docker-compose.yml
Labels: size/S

#465 Remove processing health check + recreate problem nodes
  audius-cli
  discovery-provider/chain/config.cfg
Labels: size/S

#466 fix ddex network
  discovery-provider/docker-compose.yml
Labels: size/XS

#467 Fix chain env and only recreate once
  audius-cli
Labels: size/S

#469 [PROTO-1634] Make DDEX into its own node type
  .gitignore
  audius-cli
  ddex/Caddyfile
  ddex/dev.env
  ddex/docker-compose.yml
  ddex/prod.env
  ddex/stage.env
  discovery-provider/docker-compose.yml
  install.sh
  setup.sh
Labels: size/L

#471 Add process check back
  discovery-provider/chain/config.cfg
Labels: size/XS

#472 Pass env files to DDEX ingester apps
  ddex/docker-compose.yml
Labels: size/S

#474 Move server healthcheck and bypass errors for autoheal
  discovery-provider/docker-compose.yml
Labels: size/XS

#475 Update Discovery to latest
  discovery-provider/docker-compose.yml
Labels: size/S

#473 PROTO-1574: sepolia
  creator-node/stage.env
  discovery-provider/stage.env
  identity-service/stage.env
Labels: size/S

#477 Revert "PROTO-1574: sepolia"
  creator-node/stage.env
  discovery-provider/stage.env
  identity-service/stage.env
Labels: size/S

#478 Update DDEX env vars for session and allowlist
  ddex/dev.env
  ddex/prod.env
  ddex/stage.env
Labels: size/XS

#480 Automate Mongo init and improve ddex README
  README.md
  ddex/docker-compose.yml
  install.sh
  setup.sh
Labels: size/M

#483 Launch chain before launching the stack
  audius-cli
Labels: size/XS

#482 Update ddex health checks
  ddex/docker-compose.yml
Labels: size/S

#481 add audius_ddex_apps envvar
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS
