Repository AudiusProject/audius-docker-compose, pull requests merged in 2024-10, with the labels that each got.

#537 run core everywhere
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#538 Pull discovery plugin images on upgrade
  audius-cli
Labels: size/XS

#539 log rotation for core
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/S

#541 Default to 'current' tag when unset
  creator-node/docker-compose.yml
  ddex/docker-compose.yml
  discovery-provider/docker-compose.yml
  identity-service/docker-compose.yml
Labels: size/M

#543 Use pre-existing dir for comet persistent data
  creator-node/docker-compose.yml
  discovery-provider/docker-compose.yml
Labels: size/XS

#544 Comment karma threshold
  discovery-provider/prod.env
  discovery-provider/stage.env
Labels: size/XS

#545 Add X-Forwarded-Proto header in Caddy
  discovery-provider/Caddyfile
Labels: size/XS

#546 Delete unused ddex config
  ddex/Caddyfile
  ddex/dev.env
  ddex/docker-compose.yml
  ddex/prod.env
  ddex/sources.example.json
  ddex/stage.env
Labels: size/L
