Repository AudiusProject/audius-docker-compose, pull requests merged in 2025-03, with the labels that each got.

#573 Accept direct requests via caddy
  discovery-provider/Caddyfile
Labels: size/M

#574 Up server & es memory limits
  discovery-provider/docker-compose.yml
Labels: size/XS

#578 Revert "Revert "Decom acdc (#575)""
  audius-cli
  discovery-provider/docker-compose.yml
Labels: size/L

#579 Add archiver service to compose file
  discovery-provider/docker-compose.yml
Labels: size/S

#580 Cleanup AAO port
  discovery-provider/docker-compose.yml
Labels: size/XS
